name: Restrictful
version: '0.1'
main: pl.olafcio.restrictful.Restrictful
api-version: '1.21'
load: STARTUP
authors: [ Olafcio ]
description: Restricts certain features for creative servers.
website: https://olafcio1.github.io
